### ISSUE TITLE
Non-blocking option

### ISSUE THREAD

**Issue by alfiedotwtf** [philippludwig/micro-http-server#3]
Hi,

I see that you're now allowing the user to turn off non-blocking. Are you able to push this release please?

Thanks!

https://github.com/philippludwig/micro-http-server/commit/fd9772560239f11826e40a6165abba4fe9da1554

**Comment by philippludwig** [comment]
We could have a release I guess.

**Comment by philippludwig** [comment]
Published as 0.0.5. Please excuse the delay, my Github E-Mail settings were incorrect, so I did not get notified.

**Comment by alfiedotwtf** [comment]
Awesome, thanks for that :)
